@BASE_URI=http://localhost:21000

###
GET {{BASE_URI}}/api/atlas/v2/search/basic?typeName=fs_path&query=EQ-Trading_corebanking1 HTTP/1.1
Authorization: Basic admin:admin

###


GET {{BASE_URI}}/api/atlas/v2/entity/guid/bbe468b5-9861-49c6-8ac0-af5e2503818f
